name: SMS Runner

on:
  schedule:
    - cron: "0 * * * *"   # every 1 hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 59   # auto kill before next hour

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install gspread google-auth

      - name: Create service_account.json file
        run: echo '${{ secrets.GOOGLE_CREDS }}' > service_account.json

      - name: Run script every 45 seconds for 55 minutes
        run: |
          start=$(date +%s)
          while true
          do
            python randomtest.py
            sleep 45
            now=$(date +%s)
            elapsed=$((now - start))
            if [ $elapsed -ge 3300 ]; then   # 55 minutes
              echo "Stopping before next scheduled run"
              break
            fi
          done
